name: fashion_purse_ai
channels:
  - conda-forge
  - defaults
dependencies:
  # --- CORE CIENTÍFICO ---
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - joblib

  # --- MODELADO ---
  - prophet
  - statsmodels
  - xgboost # XGBoost base (sin gpu forzado aquí para evitar error, lo activaremos después)

  # --- MLOPS ---
  - mlflow

  # --- VISUALIZACIÓN ---
  - matplotlib
  - seaborn
  - plotly

  # --- GESTOR PIP ---
  - pip
  - pip:
    # >> UI
    - streamlit>=1.30.0
    - streamlit-extras
    - streamlit-option-menu
    
    # >> DATOS
    - requests
    - tenacity
    - beautifulsoup4
    - lxml
    - pytrends
    - openpyxl
    
    # >> IA (Frameworks, NO Motores aun)
    - langchain==0.1.*
    - langchain-groq
    - langchain-community
    - langchain-huggingface
    - sentence-transformers
    - pypdf
    - tiktoken
    - ragas
    - datasets
    - python-dotenv
    - pydantic>=2.0
    - pydantic-settings
    - watchdog
